name: terraform-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Format
        run: terraform fmt -check -recursive
      - name: Validate (core)
        run: |
          set -e
          for d in $(find examples -name '*.tf' -printf '%h\n' | sort -u); do
            echo "==> $d"
            (cd "$d" && terraform init -backend=false && terraform validate || exit 1)
          done
