name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Format
      run: make fmt init DIR=examples/aws/one-time/s3_versioned_bucket VARS='-var bucket_name=my-demo-bucket-123'

    - name: Icon badge
      # You may pin to the exact commit or the version.
      # uses: damienaicheh/icon-badge-action@a39d495c4e8af27382c79c6305580998bd7afb7a
      uses: damienaicheh/icon-badge-action@v1.0.0
      
