name: validate-s3-versioned-bucket

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]


jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      ####

      - name: Terraform fmt (example only)
        working-directory: examples/aws/one-time/s3_versioned_bucket
        run: terraform fmt -check -diff -recursive

      - name: Fail if formatting changes were needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Terraform files were reformatted. Please commit the changes."
            git --no-pager diff
            exit 1
          fi
          
      - name: Terraform init (no backend)
        working-directory: examples/aws/one-time/s3_versioned_bucket
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        working-directory: examples/aws/one-time/s3_versioned_bucket
        run: terraform validate -no-color
